export {CaterpillarDemo} from './CaterpillarDemo';
export {SpiralDemo} from './SpiralDemo';
export {FinishedDemo} from './FinishedDemo';
export {ReactComponent as Spiral1} from '../assets/spiral1.svg';
export {ReactComponent as Spiral2} from '../assets/spiral2.svg';
export {ReactComponent as Spiral3} from '../assets/spiral3.svg';
export {ReactComponent as Spiral4} from '../assets/spiral4.svg';
export {ReactComponent as Spiral5} from '../assets/spiral5.svg';
export {ReactComponent as Hexagon} from '../assets/hexagon.svg';
export {ReactComponent as Pentagon} from '../assets/pentagon.svg';
